spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    session:
        timeout: 2592000
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db
        username: root
        password: root
    redis:
        host: localhost
        port: 6379
        database: 1
    servlet:
        multipart:
            max-file-size: 10MB
server:
    address: 0.0.0.0
    port: 8101
    servlet:
        context-path: /api
        session:
            cookie:
                max-age: 2592000
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: isDelete
            logic-delete-value: 1
            logic-not-delete-value: 0
knife4j:
    enable: true
    openapi:
        title: "接口文档"
        version: 1.0
        group:
            default:
                api-rule: package
                api-rule-resources:
                    - com.mcddhub.init.controller
wx:
    mp:
        token:
        aes-key:
        app-id:
        secret:
        config-storage:
            http-client-type: httpclient
            key-prefix: wx
            redis:
                host: localhost
                port: 6379
                database: 0
            type: memory
    open:
        appId: xxx
        appSecret: xxx
cos:
    client:
        accessKey: xxx
        secretKey: xxx
        region: xxx
        bucket: xxx